{% set version = "3.6.3" %}
{% set sha256 = "13b9c41ea3342b7eb0fd7f74078b5a8d5035632f05d8680266f50f4c5626c9c2" %}

package:
    name: pelican
    version: {{ version }}

source:
    fn: pelican-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pelican/pelican-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - pelican = pelican:main
        - pelican-import = pelican.tools.pelican_import:main
        - pelican-quickstart = pelican.tools.pelican_quickstart:main
        - pelican-themes = pelican.tools.pelican_themes:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - feedgenerator
        - jinja2
        - pygments
        - docutils
        - pytz
        - blinker
        - unidecode
        - six
        - python-dateutil
        - ghp-import

test:
    imports:
        - pelican
        - pelican.tools
    commands:
        - pelican --help
        - pelican-import --help
        - pelican-quickstart --help
        - pelican-themes --help

about:
    home: http://getpelican.com/
    license: AGPL-3.0
    summary: A tool to generate a static blog from reStructuredText or Markdown input files.

extra:
    recipe-maintainers:
        - ocefpaf
