travis:
  secure:
    BINSTAR_TOKEN: rpWv/PlhUoYqRx/GFKH9l8i99CtpZcFniyCY38vm5ULviXkZngLZf5R4ZqHNAyG/RdX38Bksc9gXvPmwZ/A+TJwveRn1t1aFxcNk12EXrjiicZOOsvvePkC7gdPaj1WUmnK3CW4Qg5uNfWAqDlSL48J5k/m7hMlnIIKsJvu+l5WO+RrfqiT+hUR/PlzjZvvaSRd9Pkbv1YXb6+rEBqVxlqVqNiOIOswsbkzND20TjDUU2BdoM1TxCi/3895rIooGAhpWK6ji2xTRgmD/oXmg4/ZEifeh6x/PSjfwqCUbhQMlrhJK8rFQs6HS19H7UEYZ2DPv43KdL4DAjR2xFMHpJh0zj9zfSs4oqfAZ0b8N2KYOtd3+J3OSrbDXgUxbSxxx5U95iA9CAcFeIkhm3rPCnR/5yP+nkq/lo/kBl3z8RuJivzuZf02BfG65RIH33h6McpYIGJAe4HiEeTIaYB7Ly8psILrtCyOV5GyaxYfLK0hnHfz0jWie7QQkxwjf4BDDgFEGbLcaVj6JnZEJE4iSnt0REGykQLQTd4nCouTHjWHUPuvQJPu1TVvebVzUr68XM6a92JZ6Ye7UuZIe+W2p5bZ/kiwVX0fD04pfZNx+EzaYvL0QW83RXq2xSQKvgo6ZqZdj0GqS3AFcR1ZMAccOPHv8/F3DHKF4WE2e/HEYYlg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
